"""Rebase the explicitly selected EDA files and add the approved manuscript section."""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
BASE = ROOT / 'EDA'
SCRIPTS = BASE / 'scripts'

def update(name, transform):
    p = SCRIPTS / name
    p.write_text(transform(p.read_text(encoding='utf-8')), encoding='utf-8')

def rebase(text):
    return (text.replace('parents[3]', 'parents[2]')
        .replace("ROOT/'report/EDA", "ROOT/'EDA")
        .replace("ROOT/'report/10.02_002_EDA_새원고.md'", "ROOT/'EDA/10.02_002_EDA_새원고.md'"))

update('eda_figures.py', lambda t: t[:t.index('# %% 01:')].replace(
    'Generate two PNG candidates per EDA topic from report tables; never open images.',
    'Shared plot styling for the manuscript: font, colors, and PNG export.'))
update('eda_daily_pattern.py', lambda t: rebase(t).replace(
    'Generate one two-panel PNG. Never open or visually analyze images.',
    'Generate the two-panel section 2.1 PNG; image review is separate.'))

def relations(t):
    t = t.replace('ROOT=REPORT.parent.parent','ROOT=REPORT.parent').replace('Restart EDA 2.2','Restart EDA 2.3').replace('Restarted EDA 2.2 only','Restarted EDA 2.3 only')
    # Keep direct rank-based numerical verification; retire dependencies on
    # historical, archived scripts/tables without rerunning old model work.
    start = t.index("    old=pd.read_csv(OUT/'overall_correlations.csv'")
    end = t.index('    # Follow the observed', start)
    t = t[:start] + '''    for row in overall.itertuples():
        if row.x != row.y:
            part=data[[row.x,row.y]].dropna()
            independent=np.corrcoef(stats.rankdata(part[row.x]),stats.rankdata(part[row.y]))[0,1]
            np.testing.assert_allclose(row.spearman,independent,atol=1e-12)
    for row in monthly.itertuples():
        part=data.loc[data.month.eq(row.month),[row.variable,'평균 전력']].dropna()
        independent=np.corrcoef(stats.rankdata(part[row.variable]),stats.rankdata(part['평균 전력']))[0,1]
        np.testing.assert_allclose(row.spearman,independent,atol=1e-12)
''' + t[end:]
    start = t.index("        if population in ['all','positive']:")
    end = t.index('        contexts.append', start)
    t = t[:start] + t[end:]
    start = t.index("    reference=pd.read_csv(ROOT/'EDA/jsw/tables/09.23_007_august_state_weeks.csv'")
    end = t.index('    save(pd.DataFrame([week_row])', start)
    t = t[:start] + t[end:]
    return t.replace('checked_existing_rows=len(overall)+len(monthly)+3,','checked_rank_rows=len(overall)+len(monthly)+3,').replace("'checked_existing_rows'", "'checked_rank_rows'")
update('eda_variable_relations.py', relations)

def repetition(t):
    t = rebase(t).replace('EDA 2.3 review', 'EDA 2.2 analysis')
    start = t.index("    plt.rcParams.update")
    end = t.index('    summary=', start)
    t = t[:start] + '    figures=[]  # Selected manuscript plots are generated by separate scripts.\n' + t[end:]
    return t.replace('Separate weekday/weekend heatmaps with shared absolute color scale; all-date trajectories and median/P10-P90/mean; paired change scatter.',
                     'Per-date changes and production context; hourly distributions and monthly summaries. Plotting is separate.')
update('eda_daily_repetition.py', repetition)

def simple(t):
    t = rebase(t).replace('EDA 2.3', 'EDA 2.2')
    start = t.index('    # Month-specific curves')
    end = t.index('    after=hashlib',start)
    t = t[:start] + '''    # Preserve monthly descriptive values for the independent source audit.
    matrix=pd.read_csv(TAB/'hourly_matrix.csv',encoding='utf-8-sig',index_col='date')
    matrix.index=pd.to_datetime(matrix.index)
    matrix.columns=matrix.columns.astype(int)
    dates=pd.read_csv(TAB/'daily_values.csv',encoding='utf-8-sig',index_col='date')
    dates.index=pd.to_datetime(dates.index)
    monthly=[]
    for (month,group),part in dates.groupby(['month','group']):
        values=matrix.loc[part.index]
        for hour in range(24):
            monthly.append({'month':month,'group':group,'hour':hour,'n':len(values),
                'median':float(values[hour].median()),'p10':float(values[hour].quantile(.1)),
                'p90':float(values[hour].quantile(.9))})
    monthly=pd.DataFrame(monthly)
    assert monthly.groupby(['month','group']).n.first().sum()==241
    monthly.to_csv(TAB/'monthly_hourly_distribution.csv',index=False,encoding='utf-8-sig')
''' + t[end:]
    t = t.replace("'monthly_figure':str(month_target),",'').replace('bad+month_bad','bad')
    t = t.replace('Monthly figure: two aggregated median lines per month, no band or per-date rows.',
                  'Monthly descriptive table retained for independent validation; the separate heatmap script generates the selected monthly plot.')
    return t
update('plot_daily_repetition_simple.py',simple)
update('verify_monthly_power_heatmap.py',rebase)
update('plot_monthly_power_heatmap.py', lambda t: rebase(t).replace("def main(statistic='median')", "def main(statistic='mean')").replace("default='median'", "default='mean'"))

# The moved general EDA script is narrowed to the data manuscript and the
# section 2.1 input table. Unselected peak, permutation, and lag studies stay
# in the previous report location.
(SCRIPTS/'data_overview.py').write_text('''"""Data manuscript reproduction and section 2.1 hourly summaries.

Adapted from the moved eda_analysis.py prepare/narrative calculations.
Does not train a model or change the original CSV. No plots in data chapter.
"""
from pathlib import Path
import hashlib
import json
import numpy as np
import pandas as pd

ROOT=Path(__file__).resolve().parents[2]
OUT=ROOT/'EDA/tables'
SOURCE=ROOT/'data/origin/okm_augumented_2021.csv'
SHA='8f7af2e49366c93e1d6f5fdef4b5e350066c1792ac463c2c2886e370f4674830'
SLOTS=['15분','30분','45분','60분']

def main():
    OUT.mkdir(parents=True,exist_ok=True)
    assert hashlib.sha256(SOURCE.read_bytes()).hexdigest()==SHA
    raw=pd.read_csv(SOURCE,encoding='utf-8-sig')
    scope=raw.loc[raw['날짜'].lt(20210901)].copy()
    valid=scope.loc[scope['시간'].between(0,23)].copy()
    assert raw.shape==(6168,18) and len(scope)==5832 and len(valid)==5784
    assert raw['날짜'].nunique()==257 and valid['날짜'].nunique()==241
    assert len(raw.loc[raw['날짜'].ge(20210901)])==336
    assert valid.groupby('날짜').size().eq(24).all()
    np.testing.assert_array_equal(raw['평균'],np.floor(raw[SLOTS].mean(axis=1)+.5))
    ratio=raw['生産量'] if '生産量' in raw else raw['생산량']
    ratio=ratio/raw[SLOTS].sum(axis=1)
    available=raw['공장인원'].notna()
    np.testing.assert_allclose(raw.loc[available,'공장인원'],ratio.loc[available],rtol=1e-9,atol=1e-12)
    missing=raw.isna().sum().rename_axis('variable').reset_index(name='missing_n')
    missing.to_csv(OUT/'data_missing.csv',index=False,encoding='utf-8-sig')
    assert missing.missing_n.sum()==21
    assert raw['풍속'].isna().sum()==3 and raw['강수량'].isna().sum()==1 and (~available).sum()==17
    raw.loc[raw.isna().any(axis=1),['날짜','시간','풍속','강수량','공장인원']].to_csv(
        OUT/'data_missing_records.csv',index=False,encoding='utf-8-sig')
    outliers=[]
    for variable in ['생산량','강수량']:
        v=scope[variable].dropna();q1,q3=v.quantile([.25,.75]);iqr=q3-q1
        outliers.append(dict(variable=variable,n=len(v),zero_n=int(v.eq(0).sum()),
            zero_share=float(v.eq(0).mean()),q1=float(q1),q3=float(q3),iqr=float(iqr),
            outside_iqr_n=int((v.lt(q1-1.5*iqr)|v.gt(q3+1.5*iqr)).sum()),maximum=float(v.max())))
    pd.DataFrame(outliers).to_csv(OUT/'data_distribution.csv',index=False,encoding='utf-8-sig')
    assert outliers[0]['outside_iqr_n']==533 and outliers[0]['maximum']==9830
    assert outliers[1]['outside_iqr_n']==1442 and outliers[1]['iqr']==0
    invalid=scope.loc[~scope['시간'].between(0,23)]
    assert len(invalid)==48 and set(invalid['날짜'])=={20210713,20210715}
    assert invalid['시간'].min()==70 and invalid['시간'].max()==188
    invalid[['날짜','시간']].to_csv(OUT/'data_invalid_times.csv',index=False,encoding='utf-8-sig')
    valid=valid.sort_values(['날짜','시간'])
    profiles=valid.groupby('날짜')[SLOTS].apply(lambda x:tuple(x.to_numpy().ravel()))
    multiplicity=profiles.value_counts()
    assert len(multiplicity)==126 and int(multiplicity.loc[multiplicity.gt(1)].sum())==160
    prod_unique=valid.groupby('날짜')['생산량'].nunique()
    assert prod_unique.gt(1).sum()==181 and not raw.duplicated().any()
    assert raw['생산량'].eq(0).sum()==2657
    assert (raw['생산량'].eq(0)&raw['평균'].gt(0)).sum()==2640
    assert raw[SLOTS].eq(0).all(axis=1).sum()==17
    dates=pd.to_datetime(valid['날짜'].astype(str),format='%Y%m%d')
    valid['weekend']=dates.dt.dayofweek.ge(5)
    summaries=[]
    for group,flag in [('weekday',False),('weekend',True)]:
        for hour,part in valid.loc[valid.weekend.eq(flag)].groupby('시간'):
            summaries.append(dict(population=group,hour=int(hour),n=len(part),
                production_mean=float(part['생산량'].mean()),power_mean=float(part['평균'].mean())))
    pd.DataFrame(summaries).to_csv(OUT/'hourly_overview.csv',index=False,encoding='utf-8-sig')
    # Check availability only; actual model choices remain in archived model evidence.
    series=pd.Series(valid['평균'].to_numpy(),index=dates+pd.to_timedelta(valid['시간'],unit='h'))
    grid=series.reindex(pd.date_range('2021-01-01','2021-08-31 23:00',freq='h'))
    eligible=grid.shift(1).rolling(24,min_periods=24).count().eq(24)
    for lag in (1,2,3,24,168):eligible &= grid.shift(lag).notna()
    assert int(eligible.reindex(series.index).sum())==5520
    facts=dict(status='passed',source_sha256=SHA,raw_rows=6168,columns=18,
        scope_rows=5832,valid_hours=5784,valid_days=241,missing_cells=21,
        headcount_formula_checked_rows=int(available.sum()),unique_96slot_profiles=126,
        dates_in_repeated_profiles=160,multiple_production_value_dates=181,
        eligible_history_hours=5520,model_training_performed=False)
    (OUT/'data_overview_manifest.json').write_text(json.dumps(facts,ensure_ascii=False,indent=2),encoding='utf-8')
    print(json.dumps(facts,ensure_ascii=False))

if __name__=='__main__':main()
''',encoding='utf-8')

imagebase = ROOT.as_posix() + '/EDA/figures/'
docpath=BASE/'10.02_002_EDA_새원고.md'
doc=docpath.read_text(encoding='utf-8')
doc=re.sub(r'D:/대회/제6회%20K-인공지능%20제조데이터%20분석%20경진대회/report/figures/eda/([^\)]+)',
           lambda m: '<'+imagebase+m.group(1)+'>',doc)
doc=doc.replace('tables/eda/','tables/')
doc=doc.replace('## 2.2 생산량·날씨와 전력의 관계','## 2.3 생산량·날씨와 전력의 관계')
doc=doc.replace('앞 절에서는 생산량과 전력의 하루 패턴이 완전히 일치하지 않았다.',
                '2.1에서는 생산량과 전력의 하루 패턴이 완전히 일치하지 않았고, 2.2에서는 같은 시간대라도 월과 날짜 구성에 따라 전력 수준이 달랐다.')
doc=doc.replace('다만 앞 절의 평일·주말과 시간대 차이도 포함된 전체 관계이므로',
                '다만 2.1·2.2의 평일·주말, 시간대와 월별 차이도 포함된 전체 관계이므로')
doc=doc.replace(' · [계산·그림 코드](scripts/eda_daily_pattern.py)','')
doc=doc.replace(' · [계산·그림 코드](scripts/eda_variable_relations.py)','')
doc=doc.replace('## 2.3 생산량·날씨와 전력의 관계', '''**관련 Python 코드**

- [eda_daily_pattern.py](scripts/eda_daily_pattern.py): 평일·주말의 시간대별 생산량·전력 평균을 원본과 대조하고, 이 절의 선그래프를 생성한다. 선 색·축·범례는 `main()`의 그림 생성 부분에서 수정할 수 있다.
- [data_overview.py](scripts/data_overview.py): 원본 품질을 점검하고 위 코드가 읽는 `hourly_overview.csv`를 생성한다.
- [eda_figures.py](scripts/eda_figures.py): 공통 글꼴·색상·이미지 저장 설정이다.

## 2.2 전력의 하루 패턴은 날짜와 월에 따라 어떻게 달라지는가?

2.1의 평균 선만으로는 같은 패턴이 매일 나타나는지 알기 어렵다. 같은 241일의 시간별 평균 전력을 날짜별로 비교하고, 평일·주말을 구분한 상태에서 월별 수준도 살펴봤다.

![평일과 주말의 시간대별 전력 분포](<''' + imagebase + '''daily_repetition/04_daily_pattern_simple.png>)

*실선은 날짜별 값의 중앙값, 점선은 산술평균이다. 음영은 각 시간대에서 날짜별 전력값의 10~90백분위 범위이며 신뢰구간이 아니다. 평일 171일, 주말 70일을 각각 요약했다.*

**12시 하락·13시 상승은 평일 대부분에서 나타났지만, 모든 날짜의 공통 규칙은 아니었다.** 같은 날짜의 12시 전력이 11시보다 낮고, 13시 전력이 12시보다 높은지를 확인했다. 이 조건에 해당하는 날짜는 평일 147/171일(86.0%), 주말 13/70일(18.6%)이었다. 작은 변화도 포함한 방향 비교이며, 고전력이나 피크를 분류하는 기준은 아니다.

날짜별 11→12시 변화의 중앙값은 평일 −64, 주말 −1이었고, 12→13시 변화의 중앙값은 각각 +61, 0이었다. 평일에서는 변화 폭도 컸다. 다만 하락 후 상승한 평일 147일 중 13시 전력이 11시 수준 이상으로 올라온 날짜는 51일이어서, 상승을 이전 수준으로의 완전한 회복으로 해석하지 않았다.

**예외는 생산량 기록과 함께 살펴볼 필요가 있었다.** 위 방향에 해당하지 않은 평일 24일 중 20일은 하루 동안 생산량이 모두 0이었다. 하루에 한 번이라도 양수 생산량이 기록된 평일에서는 145/149일(97.3%)에 하락 후 상승이 나타났다. 반면 주말은 양수 생산량이 있는 날짜 6/32일(18.8%), 없는 날짜 7/38일(18.4%)로 비슷했다. 생산량 기록의 유무만으로 평일·주말의 차이를 모두 설명할 수는 없었다.

### 월별 평균 전력 비교

날짜별 차이가 확인되어 전체 기간의 평균을 월별로 나눴다. 2.1과 동일한 평균 수준을 비교하기 위해 산술평균을 사용했다. 각 칸은 해당 월·평일 또는 주말·같은 시간대에 기록된 CSV ‘평균’ 값을 다시 평균한 것이다. 생산량이 0인 날짜도 포함했다.

![평일과 주말의 월별 시간대별 평균 전력](<''' + imagebase + '''daily_repetition/07_monthly_power_mean_heatmap.png>)

*두 패널은 같은 0~210 색 척도를 사용한다. 각 패널의 행은 1~8월, 열은 0~23시다. 월별 평일은 20~23일, 주말은 8~10일이며 공휴일도 해당 요일에 포함했다.*

**평일의 시간대별 형태가 비슷해도 전력 수준은 월마다 달랐다.** 예를 들어 평일 08시 평균은 7월 185.05, 8월 142.68이었다. 주말의 같은 시간 평균은 각각 23.78, 21.33이었다. 따라서 7·8월 주말의 낮은 색은 실제 기록의 평균이며, 평일의 높은 전력 기록이나 월 안의 최댓값과 모순되지 않는다.

8월 평일 08시 평균이 낮아진 데에는 날짜 구성도 포함돼 있었다. 8월 평일 22일 중 5일은 하루 동안 생산량이 모두 0이었고, 이 날짜들의 08시 평균 전력은 21.00이었다. 양수 생산량이 있는 나머지 17일의 08시 평균은 178.47이었다. 7월 평일 20일에는 모두 양수 생산량 기록이 있었다. 낮은 날짜를 제외한 결과는 구성 차이를 확인하는 보조 비교이며, 히트맵의 전체 평균을 대체하지 않는다.

이 비교는 하루 패턴이 많은 평일에서 반복되지만 날짜·월에 따라 수준이 달라진다는 것을 보여준다. 달력만으로 실제 운전 상태나 날씨의 영향을 확정할 수는 없다. 다음 절에서는 생산량과 날씨의 관계를 함께 살펴보고, 전체 관계와 월별 관계가 어떻게 다른지 비교한다.

근거: [날짜별 전력·변화](tables/daily_repetition/daily_values.csv) · [평일·주말 집계](tables/daily_repetition/group_summary.csv) · [생산 기록별 비교](tables/daily_repetition/production_context.csv) · [월·요일·시간별 평균과 표본 수](tables/daily_repetition/independent_monthly_cells.csv) · [7·8월 생산 기록 구성](tables/daily_repetition/july_august_production_composition.csv)

**관련 Python 코드**

- [eda_daily_repetition.py](scripts/eda_daily_repetition.py): 날짜별 11→12시·12→13시 변화, 평일·주말의 빈도, 생산량 기록별 차이와 시간대별 분포를 계산한다.
- [plot_daily_repetition_simple.py](scripts/plot_daily_repetition_simple.py): 위 결과표로 평균·중앙값·10~90백분위 범위의 선그래프를 생성한다. `main()`의 선·음영·축 설정에서 그림을 수정할 수 있다.
- [verify_monthly_power_heatmap.py](scripts/verify_monthly_power_heatmap.py): 원본에서 월·평일/주말·시간별 평균과 중앙값을 직접 계산해 결과표를 검증하고, 7·8월 생산량 기록 구성도 비교한다.
- [plot_monthly_power_heatmap.py](scripts/plot_monthly_power_heatmap.py): 월별 평균 히트맵을 생성한다. `main()`의 색상·색 척도·축 설정에서 그림을 수정할 수 있다. 기본값과 본문 그림은 `--statistic mean`이다.

## 2.3 생산량·날씨와 전력의 관계''',1)
doc += '''

**관련 Python 코드**

- [eda_variable_relations.py](scripts/eda_variable_relations.py): `diagnose()`에서 분포·결측·동률을 점검하고, `relations()`에서 전체·월별 Spearman 상관과 8월 생산 기록별 비교를 계산한다. `figures()`는 이 절의 두 상관 히트맵을 생성하며 색 척도·축·숫자 표시를 수정할 수 있다. 실행 옵션은 `--diagnose --figures`다.
- [eda_figures.py](scripts/eda_figures.py): 두 히트맵에 적용하는 공통 글꼴과 이미지 저장 설정이다.
'''
docpath.write_text(doc,encoding='utf-8')

datapath=BASE/'10.02_001_데이터_수록내용_선별.md'
data=datapath.read_text(encoding='utf-8').replace('../EDA/jsw/','../백업/EDA/jsw/').replace('../modeling/jsw/','../백업/modeling/jsw/')
paragraph='\n\n**관련 Python 코드:** [data_overview.py](scripts/data_overview.py)의 `main()`에서 이 절의 기록상 수치를 재현한다.'
# Insert code access at every data section, rather than making readers find a
# single chapter-wide code reference.
sections=re.split(r'(?=^## 1\.)',data,flags=re.M)
for i in range(1,len(sections)):
    block=sections[i]
    if '\n---\n' in block:
        block=block.replace('\n---\n',paragraph+' 이 절에는 플롯 이미지를 사용하지 않았다.\n\n---\n',1)
    else:
        block=block.rstrip()+paragraph+'\n\n'
    sections[i]=block
data=''.join(sections)
data += '''

*자료 생성 시점·가이드북 해석과 과거 모델의 입력·결측 처리 설명은 위 문서 근거를 따른다. `data_overview.py`는 원본 자료의 수치와 과거 입력 확보 수를 검증하며 모델을 학습하지 않는다. 과거 모델 구현은 [기본 모델 코드](../백업/modeling/jsw/scripts/09.26_001_power_models.py)와 [과거 생산·기상 입력 코드](../백업/modeling/jsw/scripts/09.26_003_past_context.py)에서 확인할 수 있다.*
'''
datapath.write_text(data,encoding='utf-8')
print('Rebased eight selected Python files; data code narrowed; manuscripts updated with section-level code links.')
